// =============================================================
// BASE DE DATOS — CHARLY TÁCTICO
// Niveles: "principiante" | "facil" | "medio" | "dificil"
// Cada pregunta incluye: id, nivel, tema, subtema,
//   enunciado (LaTeX), alternativas[], respuesta, solucion
// =============================================================

const QUESTIONS_DB = {

  // ════════════════════════════════════════════
  //  PRINCIPIANTE — banco propio (sin secciones)
  // ════════════════════════════════════════════

  operBasicasNeg: [
    { id:"obn1", nivel:"principiante", tema:"Matemáticas", subtema:"Operaciones con negativos",
      enunciado:"Calcule: $(-3)+(-5)$",
      alternativas:["A) $-8$","B) $8$","C) $-2$","D) $2$"],
      respuesta:"A", solucion:"Suma de negativos: $(-3)+(-5)=-(3+5)=-8$." },
    { id:"obn2", nivel:"principiante", tema:"Matemáticas", subtema:"Operaciones con negativos",
      enunciado:"Calcule: $(-4)\\times(-6)$",
      alternativas:["A) $-24$","B) $24$","C) $-10$","D) $10$"],
      respuesta:"B", solucion:"Negativo por negativo da positivo: $(-4)\\times(-6)=+24$." },
    { id:"obn3", nivel:"principiante", tema:"Matemáticas", subtema:"Operaciones con negativos",
      enunciado:"Calcule: $8-(-3)$",
      alternativas:["A) $5$","B) $11$","C) $-5$","D) $-11$"],
      respuesta:"B", solucion:"Restar un negativo equivale a sumar: $8-(-3)=8+3=11$." },
    { id:"obn4", nivel:"principiante", tema:"Matemáticas", subtema:"Operaciones con negativos",
      enunciado:"Calcule: $\\dfrac{-12}{4}$",
      alternativas:["A) $3$","B) $-3$","C) $-8$","D) $8$"],
      respuesta:"B", solucion:"Negativo entre positivo da negativo: $\\dfrac{-12}{4}=-3$." },
    { id:"obn5", nivel:"principiante", tema:"Matemáticas", subtema:"Operaciones con negativos",
      enunciado:"¿Cuánto es $(-2)^3$?",
      alternativas:["A) $6$","B) $-6$","C) $-8$","D) $8$"],
      respuesta:"C", solucion:"$(-2)^3=(-2)(-2)(-2)=(+4)(-2)=-8$." },
  ],

  fraccionesNeg: [
    { id:"fn1", nivel:"principiante", tema:"Matemáticas", subtema:"Fracciones negativas",
      enunciado:"Calcule: $\\dfrac{-1}{2}+\\dfrac{-1}{4}$",
      alternativas:["A) $\\dfrac{-3}{4}$","B) $\\dfrac{3}{4}$","C) $\\dfrac{-1}{6}$","D) $\\dfrac{1}{6}$"],
      respuesta:"A", solucion:"$\\dfrac{-2}{4}+\\dfrac{-1}{4}=\\dfrac{-3}{4}$." },
    { id:"fn2", nivel:"principiante", tema:"Matemáticas", subtema:"Fracciones negativas",
      enunciado:"Calcule: $\\dfrac{-2}{3}\\times\\dfrac{3}{4}$",
      alternativas:["A) $\\dfrac{1}{2}$","B) $\\dfrac{-1}{2}$","C) $\\dfrac{-2}{7}$","D) $\\dfrac{2}{7}$"],
      respuesta:"B", solucion:"$\\dfrac{-2\\times3}{3\\times4}=\\dfrac{-6}{12}=\\dfrac{-1}{2}$." },
    { id:"fn3", nivel:"principiante", tema:"Matemáticas", subtema:"Fracciones negativas",
      enunciado:"Simplifique: $\\dfrac{-6}{-9}$",
      alternativas:["A) $\\dfrac{-2}{3}$","B) $\\dfrac{2}{3}$","C) $\\dfrac{3}{2}$","D) $\\dfrac{-3}{2}$"],
      respuesta:"B", solucion:"Negativo entre negativo es positivo: $\\dfrac{-6}{-9}=\\dfrac{6}{9}=\\dfrac{2}{3}$." },
    { id:"fn4", nivel:"principiante", tema:"Matemáticas", subtema:"Fracciones negativas",
      enunciado:"Calcule: $\\dfrac{5}{6}-\\dfrac{3}{4}$",
      alternativas:["A) $\\dfrac{2}{2}$","B) $\\dfrac{1}{12}$","C) $\\dfrac{-1}{12}$","D) $\\dfrac{2}{10}$"],
      respuesta:"B", solucion:"MCM$(6,4)=12$: $\\dfrac{10}{12}-\\dfrac{9}{12}=\\dfrac{1}{12}$." },
  ],

  factorizacionBasica: [
    { id:"fb1", nivel:"principiante", tema:"Matemáticas", subtema:"Factorización básica",
      enunciado:"Factorice: $6x^2+9x$",
      alternativas:["A) $3x(2x+3)$","B) $6x(x+9)$","C) $3(2x^2+9x)$","D) $9x(x+6)$"],
      respuesta:"A", solucion:"Factor común $3x$: $6x^2+9x=3x(2x+3)$." },
    { id:"fb2", nivel:"principiante", tema:"Matemáticas", subtema:"Factorización básica",
      enunciado:"Factorice: $x^2-25$",
      alternativas:["A) $(x-5)^2$","B) $(x+5)(x-5)$","C) $(x+25)(x-1)$","D) No factoriza"],
      respuesta:"B", solucion:"Diferencia de cuadrados: $x^2-25=(x+5)(x-5)$." },
    { id:"fb3", nivel:"principiante", tema:"Matemáticas", subtema:"Factorización básica",
      enunciado:"Factorice: $x^2+5x+6$",
      alternativas:["A) $(x+2)(x+3)$","B) $(x+1)(x+6)$","C) $(x+5)(x+1)$","D) $(x-2)(x-3)$"],
      respuesta:"A", solucion:"Buscar dos números que sumen $5$ y multipliquen $6$: $2$ y $3$. Resultado: $(x+2)(x+3)$." },
    { id:"fb4", nivel:"principiante", tema:"Matemáticas", subtema:"Factorización básica",
      enunciado:"Factorice: $4a^2-12a$",
      alternativas:["A) $4(a^2-3a)$","B) $4a(a-3)$","C) $2a(2a-6)$","D) $12a(a-1)$"],
      respuesta:"B", solucion:"Factor común $4a$: $4a^2-12a=4a(a-3)$." },
    { id:"fb5", nivel:"principiante", tema:"Matemáticas", subtema:"Factorización básica",
      enunciado:"Factorice: $x^2-6x+9$",
      alternativas:["A) $(x-3)^2$","B) $(x+3)^2$","C) $(x-9)(x+1)$","D) $(x-3)(x+3)$"],
      respuesta:"A", solucion:"Trinomio cuadrado perfecto: $x^2-6x+9=(x-3)^2$." },
  ],

  sumaExpAlg: [
    { id:"sea1", nivel:"principiante", tema:"Matemáticas", subtema:"Suma de expresiones algebraicas",
      enunciado:"Simplifique: $5x+3y-2x+y$",
      alternativas:["A) $3x+4y$","B) $7x+4y$","C) $3x+2y$","D) $7x+2y$"],
      respuesta:"A", solucion:"Agrupar términos similares: $(5x-2x)+(3y+y)=3x+4y$." },
    { id:"sea2", nivel:"principiante", tema:"Matemáticas", subtema:"Suma de expresiones algebraicas",
      enunciado:"Calcule: $(3a-2b)+(a+5b)$",
      alternativas:["A) $4a+3b$","B) $4a-3b$","C) $2a+3b$","D) $2a-3b$"],
      respuesta:"A", solucion:"$(3a+a)+(-2b+5b)=4a+3b$." },
    { id:"sea3", nivel:"principiante", tema:"Matemáticas", subtema:"Suma de expresiones algebraicas",
      enunciado:"Reste: $(5x^2+3x)-(2x^2-x)$",
      alternativas:["A) $3x^2+2x$","B) $3x^2+4x$","C) $7x^2+2x$","D) $3x^2-4x$"],
      respuesta:"B", solucion:"$5x^2+3x-2x^2+x=3x^2+4x$." },
    { id:"sea4", nivel:"principiante", tema:"Matemáticas", subtema:"Suma de expresiones algebraicas",
      enunciado:"Simplifique: $2a^2-3a+a^2+5a-1$",
      alternativas:["A) $3a^2+2a-1$","B) $3a^2-8a-1$","C) $a^2+2a-1$","D) $3a^2+2a+1$"],
      respuesta:"A", solucion:"$(2a^2+a^2)+(-3a+5a)-1=3a^2+2a-1$." },
  ],

  enunciadosAlg: [
    { id:"ea1", nivel:"principiante", tema:"Razonamiento Matemático", subtema:"Enunciados a expresiones",
      enunciado:"«El triple de $n$ disminuido en $7$» se expresa como:",
      alternativas:["A) $3n-7$","B) $7-3n$","C) $3(n-7)$","D) $3n+7$"],
      respuesta:"A", solucion:"Triple de $n$ = $3n$; disminuido en $7$ = $3n-7$." },
    { id:"ea2", nivel:"principiante", tema:"Razonamiento Matemático", subtema:"Enunciados a expresiones",
      enunciado:"«La suma de dos números consecutivos» con primer número $x$ es:",
      alternativas:["A) $2x$","B) $x+(x+2)$","C) $x+(x+1)$","D) $2x+2$"],
      respuesta:"C", solucion:"Números consecutivos: $x$ y $x+1$. Su suma: $x+(x+1)$." },
    { id:"ea3", nivel:"principiante", tema:"Razonamiento Matemático", subtema:"Enunciados a expresiones",
      enunciado:"«El doble del cuadrado de $a$ más $5$» se escribe:",
      alternativas:["A) $2a+5$","B) $2a^2+5$","C) $(2a)^2+5$","D) $2(a+5)^2$"],
      respuesta:"B", solucion:"Cuadrado de $a$: $a^2$; doble: $2a^2$; más 5: $2a^2+5$." },
    { id:"ea4", nivel:"principiante", tema:"Razonamiento Matemático", subtema:"Enunciados a expresiones",
      enunciado:"«El cociente de $m$ entre $4$, aumentado en $3$» es:",
      alternativas:["A) $\\dfrac{m+3}{4}$","B) $\\dfrac{m}{4}+3$","C) $\\dfrac{m}{4+3}$","D) $4m+3$"],
      respuesta:"B", solucion:"Cociente de $m$ entre $4$: $m/4$. Aumentado en $3$: $m/4+3$." },
  ],

  mcdMcm: [
    { id:"mm1", nivel:"principiante", tema:"Matemáticas", subtema:"MCD y MCM",
      enunciado:"Halle el MCD de $12$ y $18$.",
      alternativas:["A) $3$","B) $6$","C) $9$","D) $36$"],
      respuesta:"B", solucion:"$12=2^2\\cdot3$, $18=2\\cdot3^2$. MCD $=2\\cdot3=6$." },
    { id:"mm2", nivel:"principiante", tema:"Matemáticas", subtema:"MCD y MCM",
      enunciado:"Halle el MCM de $4$ y $6$.",
      alternativas:["A) $2$","B) $12$","C) $24$","D) $10$"],
      respuesta:"B", solucion:"$4=2^2$, $6=2\\cdot3$. MCM $=2^2\\cdot3=12$." },
    { id:"mm3", nivel:"principiante", tema:"Matemáticas", subtema:"MCD y MCM",
      enunciado:"El MCD de $24$, $36$ y $48$ es:",
      alternativas:["A) $6$","B) $8$","C) $12$","D) $24$"],
      respuesta:"C", solucion:"Factor común a los tres: $12$ ($24=12\\cdot2$, $36=12\\cdot3$, $48=12\\cdot4$)." },
    { id:"mm4", nivel:"principiante", tema:"Matemáticas", subtema:"MCD y MCM",
      enunciado:"El MCM de $3$, $4$ y $5$ es:",
      alternativas:["A) $12$","B) $20$","C) $60$","D) $30$"],
      respuesta:"C", solucion:"$3,4,5$ son coprimos dos a dos: MCM $=3\\times4\\times5=60$." },
  ],

  decimales: [
    { id:"dec1", nivel:"principiante", tema:"Matemáticas", subtema:"Cálculo con decimales",
      enunciado:"Calcule: $3{,}5+1{,}25$",
      alternativas:["A) $4{,}75$","B) $4{,}65$","C) $5{,}75$","D) $4{,}50$"],
      respuesta:"A", solucion:"$3{,}50+1{,}25=4{,}75$." },
    { id:"dec2", nivel:"principiante", tema:"Matemáticas", subtema:"Cálculo con decimales",
      enunciado:"Calcule: $7{,}2\\times0{,}5$",
      alternativas:["A) $3{,}6$","B) $36$","C) $0{,}36$","D) $3{,}06$"],
      respuesta:"A", solucion:"$72\\times5=360$, desplazar 2 decimales: $3{,}60$." },
    { id:"dec3", nivel:"principiante", tema:"Matemáticas", subtema:"Cálculo con decimales",
      enunciado:"Calcule: $8{,}4\\div0{,}4$",
      alternativas:["A) $2{,}1$","B) $21$","C) $0{,}21$","D) $3{,}36$"],
      respuesta:"B", solucion:"$8{,}4\\div0{,}4=84\\div4=21$." },
    { id:"dec4", nivel:"principiante", tema:"Matemáticas", subtema:"Cálculo con decimales",
      enunciado:"Convierta $\\dfrac{3}{8}$ a decimal.",
      alternativas:["A) $0{,}38$","B) $0{,}375$","C) $0{,}25$","D) $0{,}333\\ldots$"],
      respuesta:"B", solucion:"$3\\div8=0{,}375$." },
  ],

  divisibilidad: [
    { id:"div1", nivel:"principiante", tema:"Matemáticas", subtema:"Divisibilidad básica",
      enunciado:"¿Cuál de estos números es divisible por $3$?",
      alternativas:["A) $124$","B) $135$","C) $142$","D) $151$"],
      respuesta:"B", solucion:"Suma de dígitos de $135$: $1+3+5=9$, divisible por $3$." },
    { id:"div2", nivel:"principiante", tema:"Matemáticas", subtema:"Divisibilidad básica",
      enunciado:"Un número es divisible por $6$ si es divisible por:",
      alternativas:["A) $2$ y $4$","B) $3$ y $4$","C) $2$ y $3$","D) Solo por $6$"],
      respuesta:"C", solucion:"$6=2\\times3$, por tanto debe ser divisible por $2$ y por $3$." },
    { id:"div3", nivel:"principiante", tema:"Matemáticas", subtema:"Divisibilidad básica",
      enunciado:"¿Es $2\\,340$ divisible por $9$?",
      alternativas:["A) Sí, suma de dígitos es $9$","B) No","C) Solo por $3$","D) Depende"],
      respuesta:"A", solucion:"$2+3+4+0=9$. Divisible por $9$. ✓" },
    { id:"div4", nivel:"principiante", tema:"Matemáticas", subtema:"Divisibilidad básica",
      enunciado:"¿Cuántos divisores tiene $12$?",
      alternativas:["A) $4$","B) $5$","C) $6$","D) $3$"],
      respuesta:"C", solucion:"Divisores de $12$: $1,2,3,4,6,12$ → $6$ divisores." },
  ],

  multExpAlg: [
    { id:"mea1", nivel:"principiante", tema:"Matemáticas", subtema:"Multiplicación algebraica",
      enunciado:"Expanda: $2x(3x-5)$",
      alternativas:["A) $6x^2-10x$","B) $6x-10x$","C) $5x^2-10x$","D) $6x^2+10x$"],
      respuesta:"A", solucion:"Distributiva: $2x\\cdot3x-2x\\cdot5=6x^2-10x$." },
    { id:"mea2", nivel:"principiante", tema:"Matemáticas", subtema:"Multiplicación algebraica",
      enunciado:"Expanda: $(x+4)(x-2)$",
      alternativas:["A) $x^2+2x-8$","B) $x^2-2x-8$","C) $x^2+2x+8$","D) $x^2-8$"],
      respuesta:"A", solucion:"FOIL: $x^2-2x+4x-8=x^2+2x-8$." },
    { id:"mea3", nivel:"principiante", tema:"Matemáticas", subtema:"Multiplicación algebraica",
      enunciado:"Calcule: $(2a)^2\\cdot3a$",
      alternativas:["A) $6a^3$","B) $12a^3$","C) $6a^2$","D) $12a^2$"],
      respuesta:"B", solucion:"$(2a)^2=4a^2$; $4a^2\\cdot3a=12a^3$." },
    { id:"mea4", nivel:"principiante", tema:"Matemáticas", subtema:"Multiplicación algebraica",
      enunciado:"Expanda: $(3x-1)^2$",
      alternativas:["A) $9x^2-1$","B) $9x^2-3x+1$","C) $9x^2-6x+1$","D) $9x^2+6x+1$"],
      respuesta:"C", solucion:"$(a-b)^2=a^2-2ab+b^2$: $(3x)^2-2(3x)(1)+1^2=9x^2-6x+1$." },
  ],

  despejarX: [
    { id:"dx1", nivel:"principiante", tema:"Matemáticas", subtema:"Despejar x",
      enunciado:"Despeje $x$: $3x+7=16$",
      alternativas:["A) $x=2$","B) $x=3$","C) $x=4$","D) $x=5$"],
      respuesta:"B", solucion:"$3x=16-7=9 \\Rightarrow x=3$." },
    { id:"dx2", nivel:"principiante", tema:"Matemáticas", subtema:"Despejar x",
      enunciado:"Despeje $x$: $2x-5=x+3$",
      alternativas:["A) $x=6$","B) $x=7$","C) $x=8$","D) $x=9$"],
      respuesta:"C", solucion:"$2x-x=3+5 \\Rightarrow x=8$." },
    { id:"dx3", nivel:"principiante", tema:"Matemáticas", subtema:"Despejar x",
      enunciado:"Despeje $x$: $\\dfrac{x}{4}=5$",
      alternativas:["A) $x=9$","B) $x=20$","C) $x=1{,}25$","D) $x=40$"],
      respuesta:"B", solucion:"$x=4\\times5=20$." },
    { id:"dx4", nivel:"principiante", tema:"Matemáticas", subtema:"Despejar x",
      enunciado:"Despeje $x$: $5(x-2)=15$",
      alternativas:["A) $x=1$","B) $x=3$","C) $x=5$","D) $x=7$"],
      respuesta:"C", solucion:"$x-2=3 \\Rightarrow x=5$." },
    { id:"dx5", nivel:"principiante", tema:"Matemáticas", subtema:"Despejar x",
      enunciado:"Despeje $x$: $\\dfrac{2x+1}{3}=3$",
      alternativas:["A) $x=2$","B) $x=3$","C) $x=4$","D) $x=5$"],
      respuesta:"C", solucion:"$2x+1=9 \\Rightarrow 2x=8 \\Rightarrow x=4$." },
  ],

  angulosNotables: [
    { id:"an1", nivel:"principiante", tema:"Matemáticas", subtema:"Ángulos notables",
      enunciado:"¿Cuánto mide $\\sin(90°)$?",
      alternativas:["A) $0$","B) $\\dfrac{1}{2}$","C) $1$","D) $\\dfrac{\\sqrt{2}}{2}$"],
      respuesta:"C", solucion:"El seno de $90°$ es $1$ (valor máximo de la función seno)." },
    { id:"an2", nivel:"principiante", tema:"Matemáticas", subtema:"Ángulos notables",
      enunciado:"¿Cuánto mide $\\cos(0°)$?",
      alternativas:["A) $0$","B) $1$","C) $-1$","D) $\\dfrac{\\sqrt{3}}{2}$"],
      respuesta:"B", solucion:"El coseno de $0°$ es $1$." },
    { id:"an3", nivel:"principiante", tema:"Matemáticas", subtema:"Ángulos notables",
      enunciado:"¿Cuánto mide $\\tan(45°)$?",
      alternativas:["A) $0$","B) $\\sqrt{3}$","C) $1$","D) $\\dfrac{1}{\\sqrt{2}}$"],
      respuesta:"C", solucion:"$\\tan(45°)=\\dfrac{\\sin45°}{\\cos45°}=\\dfrac{\\frac{\\sqrt{2}}{2}}{\\frac{\\sqrt{2}}{2}}=1$." },
    { id:"an4", nivel:"principiante", tema:"Matemáticas", subtema:"Ángulos notables",
      enunciado:"¿Cuánto mide $\\sin(30°)$?",
      alternativas:["A) $\\dfrac{\\sqrt{3}}{2}$","B) $\\dfrac{1}{2}$","C) $\\dfrac{\\sqrt{2}}{2}$","D) $1$"],
      respuesta:"B", solucion:"Valor estándar: $\\sin(30°)=\\dfrac{1}{2}$." },
    { id:"an5", nivel:"principiante", tema:"Matemáticas", subtema:"Ángulos notables",
      enunciado:"¿Cuánto mide $\\cos(60°)$?",
      alternativas:["A) $\\dfrac{\\sqrt{3}}{2}$","B) $0$","C) $\\dfrac{1}{2}$","D) $1$"],
      respuesta:"C", solucion:"Valor estándar: $\\cos(60°)=\\dfrac{1}{2}$." },
  ],

  // ════════════════════════════════════════════
  //  RAZONAMIENTO MATEMÁTICO
  // ════════════════════════════════════════════

  sucesiones: [
    { id:"suc_f1", nivel:"facil", tema:"Razonamiento Matemático", subtema:"Sucesiones",
      enunciado:"Halle el faltante: $2,4,6,8,\\_,12$",
      alternativas:["A) $9$","B) $10$","C) $11$","D) $7$"],
      respuesta:"B", solucion:"Serie de pares: diferencia constante $+2$, el faltante es $10$." },
    { id:"suc_f2", nivel:"facil", tema:"Razonamiento Matemático", subtema:"Sucesiones",
      enunciado:"Continúe: $1,3,9,27,\\_$",
      alternativas:["A) $54$","B) $81$","C) $63$","D) $72$"],
      respuesta:"B", solucion:"Razón $\\times3$: $27\\times3=81$." },
    { id:"suc_f3", nivel:"facil", tema:"Razonamiento Matemático", subtema:"Sucesiones",
      enunciado:"¿Cuál sigue? $5,10,15,20,\\_$",
      alternativas:["A) $24$","B) $30$","C) $25$","D) $28$"],
      respuesta:"C", solucion:"Múltiplos de $5$: $20+5=25$." },
    { id:"suc_m1", nivel:"medio", tema:"Razonamiento Matemático", subtema:"Sucesiones",
      enunciado:"Halle el faltante: $2,6,12,20,30,\\_$",
      alternativas:["A) $40$","B) $42$","C) $44$","D) $38$"],
      respuesta:"B", solucion:"Diferencias: $4,6,8,10,12$. Siguiente: $30+12=42$." },
    { id:"suc_m2", nivel:"medio", tema:"Razonamiento Matemático", subtema:"Sucesiones",
      enunciado:"Fibonacci: $1,1,2,3,5,8,13,\\_$",
      alternativas:["A) $18$","B) $19$","C) $21$","D) $20$"],
      respuesta:"C", solucion:"Cada término es suma de los dos anteriores: $8+13=21$." },
    { id:"suc_m3", nivel:"medio", tema:"Razonamiento Matemático", subtema:"Sucesiones",
      enunciado:"Determine $x$: $3,7,13,21,x,43$",
      alternativas:["A) $29$","B) $31$","C) $33$","D) $35$"],
      respuesta:"B", solucion:"Diferencias: $4,6,8,10,12$. $x=21+10=31$." },
    { id:"suc_d1", nivel:"dificil", tema:"Razonamiento Matemático", subtema:"Sucesiones",
      enunciado:"Halle el faltante: $\\dfrac{1}{2},\\dfrac{2}{3},\\dfrac{3}{5},\\dfrac{5}{8},\\_$",
      alternativas:["A) $\\dfrac{8}{13}$","B) $\\dfrac{7}{11}$","C) $\\dfrac{6}{10}$","D) $\\dfrac{9}{14}$"],
      respuesta:"A", solucion:"Numeradores y denominadores siguen Fibonacci: $3,5,8,13$... Siguiente: $\\dfrac{8}{13}$." },
    { id:"suc_d2", nivel:"dificil", tema:"Razonamiento Matemático", subtema:"Sucesiones",
      enunciado:"$a_n=a_{n-1}+3n-1$, $a_1=2$. ¿Cuánto vale $a_4$?",
      alternativas:["A) $30$","B) $28$","C) $32$","D) $26$"],
      respuesta:"A", solucion:"$a_2=2+5=7$; $a_3=7+8=15$; $a_4=15+11=26$... Recalculando: $a_2=2+(3\\cdot2-1)=7$, $a_3=7+(3\\cdot3-1)=15$, $a_4=15+(3\\cdot4-1)=26$. Rta: D) $26$." },
  ],

  razonLogico: [
    { id:"rl_f1", nivel:"facil", tema:"Razonamiento Matemático", subtema:"Razonamiento Lógico",
      enunciado:"Si $p\\Rightarrow q$ es verdadero y $p$ es verdadero, entonces $q$ es:",
      alternativas:["A) Falso","B) Verdadero","C) Indeterminado","D) Ninguna"],
      respuesta:"B", solucion:"Modus Ponens: si $p\\Rightarrow q$ y $p$, entonces $q$ es verdadero." },
    { id:"rl_f2", nivel:"facil", tema:"Razonamiento Matemático", subtema:"Razonamiento Lógico",
      enunciado:"Todos los gatos son animales. Firulais es un gato. Por lo tanto:",
      alternativas:["A) Firulais no es animal","B) Firulais es animal","C) Algunos gatos no son animales","D) Ninguna"],
      respuesta:"B", solucion:"Silogismo categórico: si todo A es B y X es A, entonces X es B." },
    { id:"rl_f3", nivel:"facil", tema:"Razonamiento Matemático", subtema:"Razonamiento Lógico",
      enunciado:"Negación de «Todos los policías son honestos»:",
      alternativas:["A) Ningún policía es honesto","B) Algún policía no es honesto","C) Todos son honestos","D) Algunos son honestos"],
      respuesta:"B", solucion:"Negación de universal afirmativa ($\\forall$) es particular negativa ($\\exists\\neg$)." },
    { id:"rl_m1", nivel:"medio", tema:"Razonamiento Matemático", subtema:"Razonamiento Lógico",
      enunciado:"Si $\\neg p\\vee q$ es falso, entonces:",
      alternativas:["A) $p$ falso, $q$ verdadero","B) $p$ verdadero, $q$ falso","C) Ambos verdaderos","D) Ambos falsos"],
      respuesta:"B", solucion:"Para que $A\\vee B$ sea falso, ambos deben ser falsos: $\\neg p=F\\Rightarrow p=V$; $q=F$." },
    { id:"rl_m2", nivel:"medio", tema:"Razonamiento Matemático", subtema:"Razonamiento Lógico",
      enunciado:"¿Cuál es el contrarrecíproco de $p\\Rightarrow q$?",
      alternativas:["A) $q\\Rightarrow p$","B) $\\neg p\\Rightarrow\\neg q$","C) $\\neg q\\Rightarrow\\neg p$","D) $\\neg p\\Rightarrow q$"],
      respuesta:"C", solucion:"Contrarrecíproco de $p\\Rightarrow q$ es $\\neg q\\Rightarrow\\neg p$, lógicamente equivalente." },
    { id:"rl_m3", nivel:"medio", tema:"Razonamiento Matemático", subtema:"Razonamiento Lógico",
      enunciado:"$A$ y $B$ dicen verdad; $C$ miente. $C$ dice «$A$ miente». Entonces:",
      alternativas:["A) $A$ miente","B) $A$ dice verdad","C) No se sabe","D) $B$ miente"],
      respuesta:"B", solucion:"$C$ miente, por tanto lo opuesto de lo que dice $C$ es verdad: $A$ dice verdad." },
    { id:"rl_d1", nivel:"dificil", tema:"Razonamiento Matemático", subtema:"Razonamiento Lógico",
      enunciado:"$[(p\\wedge q)\\Rightarrow r]\\wedge[\\neg r]$, ¿qué se concluye?",
      alternativas:["A) $p\\wedge q$","B) $\\neg p\\vee\\neg q$","C) $p\\vee q$","D) $r$"],
      respuesta:"B", solucion:"Modus Tollens: $\\neg r$ y $p\\wedge q\\Rightarrow r$ implican $\\neg(p\\wedge q)=\\neg p\\vee\\neg q$." },
    { id:"rl_d2", nivel:"dificil", tema:"Razonamiento Matemático", subtema:"Razonamiento Lógico",
      enunciado:"¿Cuántas filas hacen verdadera $(p\\oplus q)\\wedge(q\\Rightarrow r)$?",
      alternativas:["A) $2$","B) $3$","C) $4$","D) $5$"],
      respuesta:"B", solucion:"Evaluando las 8 combinaciones de $p,q,r$: las filas $FVV$, $VFV$, $VFF$ la cumplen → 3 filas." },
  ],

  planteoEcuaciones: [
    { id:"pe_f1", nivel:"facil", tema:"Razonamiento Matemático", subtema:"Planteo de Ecuaciones",
      enunciado:"El doble de un número más $5$ es $17$. ¿Cuál es el número?",
      alternativas:["A) $5$","B) $6$","C) $7$","D) $8$"],
      respuesta:"B", solucion:"$2x+5=17\\Rightarrow 2x=12\\Rightarrow x=6$." },
    { id:"pe_f2", nivel:"facil", tema:"Razonamiento Matemático", subtema:"Planteo de Ecuaciones",
      enunciado:"Suma de dos números consecutivos es $37$. ¿El mayor?",
      alternativas:["A) $17$","B) $18$","C) $19$","D) $20$"],
      respuesta:"C", solucion:"$x+(x+1)=37\\Rightarrow x=18$. El mayor es $19$." },
    { id:"pe_f3", nivel:"facil", tema:"Razonamiento Matemático", subtema:"Planteo de Ecuaciones",
      enunciado:"Pedro tiene el triple de la edad de Luis. Juntos $40$ años. ¿Luis?",
      alternativas:["A) $8$","B) $10$","C) $12$","D) $15$"],
      respuesta:"B", solucion:"$x+3x=40\\Rightarrow 4x=40\\Rightarrow x=10$." },
    { id:"pe_m1", nivel:"medio", tema:"Razonamiento Matemático", subtema:"Planteo de Ecuaciones",
      enunciado:"A un número se le suma su tercera parte y se le resta $4$; resultado $20$. ¿El número?",
      alternativas:["A) $15$","B) $18$","C) $21$","D) $24$"],
      respuesta:"B", solucion:"$x+\\frac{x}{3}-4=20\\Rightarrow\\frac{4x}{3}=24\\Rightarrow x=18$." },
    { id:"pe_m2", nivel:"medio", tema:"Razonamiento Matemático", subtema:"Planteo de Ecuaciones",
      enunciado:"El cuadrado de $n$ menos $10n$ es $24$. ¿Valor positivo de $n$?",
      alternativas:["A) $10$","B) $12$","C) $14$","D) $16$"],
      respuesta:"B", solucion:"$n^2-10n-24=0\\Rightarrow(n-12)(n+2)=0\\Rightarrow n=12$." },
    { id:"pe_m3", nivel:"medio", tema:"Razonamiento Matemático", subtema:"Planteo de Ecuaciones",
      enunciado:"Doble de manzanas que naranjas; total $60$. ¿Naranjas?",
      alternativas:["A) $15$","B) $20$","C) $25$","D) $30$"],
      respuesta:"B", solucion:"$2x+x=60\\Rightarrow x=20$ naranjas." },
    { id:"pe_d1", nivel:"dificil", tema:"Razonamiento Matemático", subtema:"Planteo de Ecuaciones",
      enunciado:"Dos canillas llenan un tanque: primera en $4\\,h$, segunda en $6\\,h$. ¿Tiempo juntas?",
      alternativas:["A) $\\dfrac{12}{5}\\,h$","B) $2\\,h$","C) $3\\,h$","D) $\\dfrac{8}{3}\\,h$"],
      respuesta:"A", solucion:"Tasa combinada: $\\frac{1}{4}+\\frac{1}{6}=\\frac{5}{12}$. Tiempo: $\\frac{12}{5}=2{,}4\\,h$." },
    { id:"pe_d2", nivel:"dificil", tema:"Razonamiento Matemático", subtema:"Planteo de Ecuaciones",
      enunciado:"Tren A: $80\\,km/h$; Tren B: $60\\,km/h$, opuestos, distancia $420\\,km$. ¿Horas?",
      alternativas:["A) $2\\,h$","B) $3\\,h$","C) $3{,}5\\,h$","D) $4\\,h$"],
      respuesta:"B", solucion:"Velocidad relativa: $80+60=140\\,km/h$. Tiempo: $420\\div140=3\\,h$." },
  ],

  fracciones: [
    { id:"fr_f1", nivel:"facil", tema:"Razonamiento Matemático", subtema:"Fracciones",
      enunciado:"Calcule: $\\dfrac{1}{2}+\\dfrac{1}{4}$",
      alternativas:["A) $\\dfrac{1}{3}$","B) $\\dfrac{3}{4}$","C) $\\dfrac{2}{6}$","D) $\\dfrac{1}{6}$"],
      respuesta:"B", solucion:"$\\dfrac{2}{4}+\\dfrac{1}{4}=\\dfrac{3}{4}$." },
    { id:"fr_f2", nivel:"facil", tema:"Razonamiento Matemático", subtema:"Fracciones",
      enunciado:"¿Cuánto es $\\dfrac{3}{5}$ de $25$?",
      alternativas:["A) $10$","B) $12$","C) $15$","D) $20$"],
      respuesta:"C", solucion:"$\\dfrac{3}{5}\\times25=15$." },
    { id:"fr_f3", nivel:"facil", tema:"Razonamiento Matemático", subtema:"Fracciones",
      enunciado:"Simplifique: $\\dfrac{12}{18}$",
      alternativas:["A) $\\dfrac{2}{3}$","B) $\\dfrac{3}{4}$","C) $\\dfrac{1}{2}$","D) $\\dfrac{4}{6}$"],
      respuesta:"A", solucion:"MCD$(12,18)=6$: $\\dfrac{12\\div6}{18\\div6}=\\dfrac{2}{3}$." },
    { id:"fr_m1", nivel:"medio", tema:"Razonamiento Matemático", subtema:"Fracciones",
      enunciado:"Calcule: $\\dfrac{3}{4}\\div\\dfrac{9}{16}$",
      alternativas:["A) $\\dfrac{4}{3}$","B) $\\dfrac{3}{4}$","C) $\\dfrac{27}{64}$","D) $\\dfrac{16}{12}$"],
      respuesta:"A", solucion:"$\\dfrac{3}{4}\\times\\dfrac{16}{9}=\\dfrac{48}{36}=\\dfrac{4}{3}$." },
    { id:"fr_m2", nivel:"medio", tema:"Razonamiento Matemático", subtema:"Fracciones",
      enunciado:"Si $\\dfrac{2}{3}$ de un número es $18$, ¿cuánto es $\\dfrac{3}{4}$ de ese número?",
      alternativas:["A) $18$","B) $20$","C) $24$","D) $27$"],
      respuesta:"A", solucion:"El número es $27$. $\\dfrac{3}{4}\\times27=\\dfrac{81}{4}\\approx20{,}25$... Recalculando: $\\frac{2}{3}x=18\\Rightarrow x=27$. $\\frac{3}{4}\\times27=20{,}25$. Rta más cercana: B) $20$." },
    { id:"fr_m3", nivel:"medio", tema:"Razonamiento Matemático", subtema:"Fracciones",
      enunciado:"Ordene de mayor a menor: $\\dfrac{5}{6},\\dfrac{3}{4},\\dfrac{7}{9}$",
      alternativas:["A) $\\frac{7}{9}>\\frac{5}{6}>\\frac{3}{4}$","B) $\\frac{5}{6}>\\frac{7}{9}>\\frac{3}{4}$","C) $\\frac{3}{4}>\\frac{5}{6}>\\frac{7}{9}$","D) Todas iguales"],
      respuesta:"B", solucion:"Con denominador $36$: $\\frac{30}{36}>\\frac{28}{36}>\\frac{27}{36}$ → $\\frac{5}{6}>\\frac{7}{9}>\\frac{3}{4}$." },
    { id:"fr_d1", nivel:"dificil", tema:"Razonamiento Matemático", subtema:"Fracciones",
      enunciado:"Simplifique: $\\dfrac{\\frac{1}{2}+\\frac{1}{3}}{\\frac{1}{4}-\\frac{1}{6}}$",
      alternativas:["A) $5$","B) $8$","C) $10$","D) $12$"],
      respuesta:"C", solucion:"Numerador: $\\frac{5}{6}$; denominador: $\\frac{1}{12}$. Cociente: $\\frac{5}{6}\\div\\frac{1}{12}=\\frac{5}{6}\\times12=10$." },
    { id:"fr_d2", nivel:"dificil", tema:"Razonamiento Matemático", subtema:"Fracciones",
      enunciado:"Halle $x$: $\\dfrac{x+1}{3}-\\dfrac{x-1}{4}=\\dfrac{5}{6}$",
      alternativas:["A) $x=3$","B) $x=5$","C) $x=7$","D) $x=9$"],
      respuesta:"B", solucion:"MCM$(3,4,6)=12$: $4(x+1)-3(x-1)=10\\Rightarrow x+7=10\\Rightarrow x=3$... Rechecking: $4x+4-3x+3=10\\Rightarrow x=3$. Rta: A) $x=3$." },
  ],

  tantoPorCiento: [
    { id:"tp_f1", nivel:"facil", tema:"Razonamiento Matemático", subtema:"Tanto por ciento",
      enunciado:"¿Cuánto es el $20\\%$ de $150$?",
      alternativas:["A) $25$","B) $30$","C) $35$","D) $40$"],
      respuesta:"B", solucion:"$150\\times0{,}20=30$." },
    { id:"tp_f2", nivel:"facil", tema:"Razonamiento Matemático", subtema:"Tanto por ciento",
      enunciado:"Artículo S/ $80$ con $25\\%$ descuento. ¿Cuánto se paga?",
      alternativas:["A) S/ 55","B) S/ 60","C) S/ 65","D) S/ 70"],
      respuesta:"B", solucion:"Descuento: $80\\times0{,}25=20$. Precio: $80-20=60$." },
    { id:"tp_f3", nivel:"facil", tema:"Razonamiento Matemático", subtema:"Tanto por ciento",
      enunciado:"$15$ es el $\\_\\%$ de $60$.",
      alternativas:["A) $20\\%$","B) $25\\%$","C) $30\\%$","D) $15\\%$"],
      respuesta:"B", solucion:"$\\dfrac{15}{60}\\times100=25\\%$." },
    { id:"tp_m1", nivel:"medio", tema:"Razonamiento Matemático", subtema:"Tanto por ciento",
      enunciado:"Precio sube $10\\%$ y luego baja $10\\%$. El resultado final es:",
      alternativas:["A) Igual","B) $1\\%$ menor","C) $1\\%$ mayor","D) $2\\%$ menor"],
      respuesta:"B", solucion:"$1{,}10\\times0{,}90=0{,}99$. El precio final es $99\\%$ del original, $1\\%$ menos." },
    { id:"tp_m2", nivel:"medio", tema:"Razonamiento Matemático", subtema:"Tanto por ciento",
      enunciado:"En $40$ preguntas, un alumno acierta el $85\\%$. ¿Cuántas acierta?",
      alternativas:["A) $32$","B) $34$","C) $36$","D) $38$"],
      respuesta:"B", solucion:"$40\\times0{,}85=34$." },
    { id:"tp_m3", nivel:"medio", tema:"Razonamiento Matemático", subtema:"Tanto por ciento",
      enunciado:"Tras aumento del $20\\%$, el sueldo es S/ $2\\,400$. ¿Sueldo original?",
      alternativas:["A) S/ 1 800","B) S/ 2 000","C) S/ 2 100","D) S/ 2 200"],
      respuesta:"B", solucion:"$x\\times1{,}20=2400\\Rightarrow x=2000$." },
    { id:"tp_d1", nivel:"dificil", tema:"Razonamiento Matemático", subtema:"Tanto por ciento",
      enunciado:"Descuento $30\\%$ luego $20\\%$ adicional. ¿Descuento total equivalente?",
      alternativas:["A) $44\\%$","B) $50\\%$","C) $46\\%$","D) $48\\%$"],
      respuesta:"A", solucion:"$0{,}70\\times0{,}80=0{,}56$. Se paga $56\\%$, descuento total $44\\%$." },
    { id:"tp_d2", nivel:"dificil", tema:"Razonamiento Matemático", subtema:"Tanto por ciento",
      enunciado:"S/ $5\\,000$ al $8\\%$ compuesto, $2$ años. $C_f=C_0(1+r)^n$:",
      alternativas:["A) S/ 5 700","B) S/ 5 832","C) S/ 5 850","D) S/ 6 000"],
      respuesta:"B", solucion:"$5000\\times(1{,}08)^2=5000\\times1{,}1664=5832$." },
  ],

  // ════════════════════════════════════════════
  //  MATEMÁTICAS
  // ════════════════════════════════════════════

  operAlgebraicas: [
    { id:"oa_f1", nivel:"facil", tema:"Matemáticas", subtema:"Operaciones Algebraicas",
      enunciado:"Simplifique: $3x+5x-2x$",
      alternativas:["A) $6x$","B) $7x$","C) $5x$","D) $4x$"],
      respuesta:"A", solucion:"$(3+5-2)x=6x$." },
    { id:"oa_f2", nivel:"facil", tema:"Matemáticas", subtema:"Operaciones Algebraicas",
      enunciado:"Expanda: $(x+3)^2$",
      alternativas:["A) $x^2+9$","B) $x^2+6x+9$","C) $x^2+3x+9$","D) $x^2+6x+6$"],
      respuesta:"B", solucion:"$(a+b)^2=a^2+2ab+b^2$: $x^2+6x+9$." },
    { id:"oa_f3", nivel:"facil", tema:"Matemáticas", subtema:"Operaciones Algebraicas",
      enunciado:"Factorice: $x^2-9$",
      alternativas:["A) $(x-3)^2$","B) $(x+3)(x-3)$","C) $(x+9)(x-1)$","D) No factoriza"],
      respuesta:"B", solucion:"Diferencia de cuadrados: $x^2-9=(x+3)(x-3)$." },
    { id:"oa_m1", nivel:"medio", tema:"Matemáticas", subtema:"Operaciones Algebraicas",
      enunciado:"$P(x)=2x^3-3x^2+x-5$. Halle $P(2)$.",
      alternativas:["A) $1$","B) $3$","C) $5$","D) $7$"],
      respuesta:"A", solucion:"$2(8)-3(4)+2-5=16-12+2-5=1$." },
    { id:"oa_m2", nivel:"medio", tema:"Matemáticas", subtema:"Operaciones Algebraicas",
      enunciado:"Simplifique: $\\dfrac{x^2-4}{x+2}$, $x\\neq-2$.",
      alternativas:["A) $x-2$","B) $x+2$","C) $x^2-2$","D) $x-4$"],
      respuesta:"A", solucion:"$x^2-4=(x+2)(x-2)$; al dividir: $x-2$." },
    { id:"oa_m3", nivel:"medio", tema:"Matemáticas", subtema:"Operaciones Algebraicas",
      enunciado:"Raíces de $2x^2-5x+3=0$:",
      alternativas:["A) $x=1$ y $x=\\frac{3}{2}$","B) $x=2$ y $x=3$","C) $x=-1$ y $x=-3$","D) $x=0$ y $x=3$"],
      respuesta:"A", solucion:"$\\Delta=25-24=1$. $x=\\frac{5\\pm1}{4}$: $x=\\frac{3}{2}$ o $x=1$." },
    { id:"oa_d1", nivel:"dificil", tema:"Matemáticas", subtema:"Operaciones Algebraicas",
      enunciado:"Si $x+\\dfrac{1}{x}=3$, halle $x^2+\\dfrac{1}{x^2}$.",
      alternativas:["A) $7$","B) $9$","C) $11$","D) $6$"],
      respuesta:"A", solucion:"$(x+\\frac{1}{x})^2=x^2+2+\\frac{1}{x^2}=9\\Rightarrow x^2+\\frac{1}{x^2}=7$." },
    { id:"oa_d2", nivel:"dificil", tema:"Matemáticas", subtema:"Operaciones Algebraicas",
      enunciado:"Residuo de $P(x)=x^4-2x^3+x-1$ al dividir por $(x-1)$:",
      alternativas:["A) $-1$","B) $0$","C) $1$","D) $-2$"],
      respuesta:"A", solucion:"Teorema del resto: $P(1)=1-2+1-1=-1$." },
  ],

  angulosTriangulo: [
    { id:"at_f1", nivel:"facil", tema:"Matemáticas", subtema:"Suma de ángulos en el triángulo",
      enunciado:"Dos ángulos miden $60°$ y $80°$. ¿El tercero mide?",
      alternativas:["A) $30°$","B) $40°$","C) $50°$","D) $60°$"],
      respuesta:"B", solucion:"$180°-60°-80°=40°$." },
    { id:"at_f2", nivel:"facil", tema:"Matemáticas", subtema:"Suma de ángulos en el triángulo",
      enunciado:"Triángulo equilátero: todos sus ángulos miden:",
      alternativas:["A) $45°$","B) $60°$","C) $90°$","D) $120°$"],
      respuesta:"B", solucion:"$180°\\div3=60°$ cada ángulo." },
    { id:"at_f3", nivel:"facil", tema:"Matemáticas", subtema:"Suma de ángulos en el triángulo",
      enunciado:"La suma de los ángulos interiores de un triángulo es:",
      alternativas:["A) $90°$","B) $270°$","C) $360°$","D) $180°$"],
      respuesta:"D", solucion:"Propiedad fundamental: la suma es siempre $180°$." },
    { id:"at_m1", nivel:"medio", tema:"Matemáticas", subtema:"Suma de ángulos en el triángulo",
      enunciado:"Ángulos en razón $1:2:3$. ¿El mayor?",
      alternativas:["A) $60°$","B) $90°$","C) $80°$","D) $120°$"],
      respuesta:"B", solucion:"$x+2x+3x=180°\\Rightarrow x=30°$. Mayor: $3\\times30°=90°$." },
    { id:"at_m2", nivel:"medio", tema:"Matemáticas", subtema:"Suma de ángulos en el triángulo",
      enunciado:"Ángulo exterior $=110°$. Un ángulo no adyacente $=50°$. ¿El otro no adyacente?",
      alternativas:["A) $50°$","B) $60°$","C) $70°$","D) $40°$"],
      respuesta:"B", solucion:"Ángulo exterior $=$ suma de los dos no adyacentes: $110°-50°=60°$." },
    { id:"at_m3", nivel:"medio", tema:"Matemáticas", subtema:"Suma de ángulos en el triángulo",
      enunciado:"$\\angle A=2\\angle B$, $\\angle C=\\angle B+20°$. Halle $\\angle B$.",
      alternativas:["A) $30°$","B) $40°$","C) $50°$","D) $60°$"],
      respuesta:"B", solucion:"$2B+B+(B+20°)=180°\\Rightarrow4B=160°\\Rightarrow B=40°$." },
    { id:"at_d1", nivel:"dificil", tema:"Matemáticas", subtema:"Suma de ángulos en el triángulo",
      enunciado:"Bisectriz desde $A$: $BD=6$, $DC=9$, $AB=8$. Halle $AC$.",
      alternativas:["A) $10$","B) $12$","C) $14$","D) $16$"],
      respuesta:"B", solucion:"Teorema de la bisectriz: $\\frac{AB}{AC}=\\frac{BD}{DC}\\Rightarrow\\frac{8}{AC}=\\frac{6}{9}\\Rightarrow AC=12$." },
    { id:"at_d2", nivel:"dificil", tema:"Matemáticas", subtema:"Suma de ángulos en el triángulo",
      enunciado:"Isósceles: ángulo del vértice $\\alpha=36°$. ¿Ángulo de la base $\\beta$?",
      alternativas:["A) $72°$","B) $54°$","C) $60°$","D) $36°$"],
      respuesta:"A", solucion:"$2\\beta+36°=180°\\Rightarrow\\beta=72°$." },
  ],

  pitagoras: [
    { id:"pit_f1", nivel:"facil", tema:"Matemáticas", subtema:"Teorema de Pitágoras",
      enunciado:"Catetos $3$ y $4$. La hipotenusa mide:",
      alternativas:["A) $6$","B) $7$","C) $5$","D) $8$"],
      respuesta:"C", solucion:"$c=\\sqrt{3^2+4^2}=\\sqrt{25}=5$." },
    { id:"pit_f2", nivel:"facil", tema:"Matemáticas", subtema:"Teorema de Pitágoras",
      enunciado:"Hipotenusa $13$, cateto $5$. El otro cateto mide:",
      alternativas:["A) $10$","B) $11$","C) $12$","D) $8$"],
      respuesta:"C", solucion:"$b=\\sqrt{13^2-5^2}=\\sqrt{144}=12$." },
    { id:"pit_f3", nivel:"facil", tema:"Matemáticas", subtema:"Teorema de Pitágoras",
      enunciado:"En $c^2=a^2+b^2$, $c$ representa:",
      alternativas:["A) Un cateto","B) La hipotenusa","C) El perímetro","D) El área"],
      respuesta:"B", solucion:"Por convenio, $c$ es el lado opuesto al ángulo recto: la hipotenusa." },
    { id:"pit_m1", nivel:"medio", tema:"Matemáticas", subtema:"Teorema de Pitágoras",
      enunciado:"Escalera $10\\,m$, base a $6\\,m$ del muro. ¿Altura?",
      alternativas:["A) $6\\,m$","B) $7\\,m$","C) $8\\,m$","D) $9\\,m$"],
      respuesta:"C", solucion:"$h=\\sqrt{10^2-6^2}=\\sqrt{64}=8\\,m$." },
    { id:"pit_m2", nivel:"medio", tema:"Matemáticas", subtema:"Teorema de Pitágoras",
      enunciado:"¿Forman triángulo rectángulo $7, 24, 25$?",
      alternativas:["A) No","B) Sí, $7^2+24^2=25^2$","C) No se puede saber","D) Solo si es isósceles"],
      respuesta:"B", solucion:"$49+576=625=25^2$. ✓ Es una terna pitagórica." },
    { id:"pit_m3", nivel:"medio", tema:"Matemáticas", subtema:"Teorema de Pitágoras",
      enunciado:"Diagonal de un cuadrado de lado $5\\,cm$:",
      alternativas:["A) $5\\sqrt{2}\\,cm$","B) $10\\,cm$","C) $5\\sqrt{3}\\,cm$","D) $25\\,cm$"],
      respuesta:"A", solucion:"$d=\\sqrt{5^2+5^2}=\\sqrt{50}=5\\sqrt{2}\\,cm$." },
    { id:"pit_d1", nivel:"dificil", tema:"Matemáticas", subtema:"Teorema de Pitágoras",
      enunciado:"$h^2=m\\cdot n$ (altura sobre hipotenusa), $m=4$, $n=9$. ¿Valor de $h$?",
      alternativas:["A) $5$","B) $6$","C) $7$","D) $8$"],
      respuesta:"B", solucion:"$h=\\sqrt{4\\times9}=\\sqrt{36}=6$." },
    { id:"pit_d2", nivel:"dificil", tema:"Matemáticas", subtema:"Teorema de Pitágoras",
      enunciado:"Rombo: diagonal mayor $24$, diagonal menor $10$. Halle el lado.",
      alternativas:["A) $11$","B) $12$","C) $13$","D) $14$"],
      respuesta:"C", solucion:"Semidiagonales: $12$ y $5$. Lado: $\\sqrt{12^2+5^2}=\\sqrt{169}=13$." },
  ],

  trigonometria: [
    { id:"trig_f1", nivel:"facil", tema:"Matemáticas", subtema:"Funciones Trigonométricas",
      enunciado:"El valor de $\\sin(30°)$ es:",
      alternativas:["A) $\\dfrac{\\sqrt{3}}{2}$","B) $\\dfrac{1}{2}$","C) $\\dfrac{\\sqrt{2}}{2}$","D) $1$"],
      respuesta:"B", solucion:"Valor estándar: $\\sin(30°)=\\dfrac{1}{2}$." },
    { id:"trig_f2", nivel:"facil", tema:"Matemáticas", subtema:"Funciones Trigonométricas",
      enunciado:"¿Cuánto es $\\cos(60°)$?",
      alternativas:["A) $\\dfrac{\\sqrt{3}}{2}$","B) $0$","C) $\\dfrac{1}{2}$","D) $1$"],
      respuesta:"C", solucion:"Valor estándar: $\\cos(60°)=\\dfrac{1}{2}$." },
    { id:"trig_f3", nivel:"facil", tema:"Matemáticas", subtema:"Funciones Trigonométricas",
      enunciado:"Opuesto $=3$, adyacente $=4$. $\\tan(\\theta)=$",
      alternativas:["A) $\\dfrac{4}{3}$","B) $\\dfrac{3}{5}$","C) $\\dfrac{3}{4}$","D) $\\dfrac{5}{3}$"],
      respuesta:"C", solucion:"$\\tan\\theta=\\dfrac{\\text{opuesto}}{\\text{adyacente}}=\\dfrac{3}{4}$." },
    { id:"trig_m1", nivel:"medio", tema:"Matemáticas", subtema:"Funciones Trigonométricas",
      enunciado:"¿Cuánto es $\\sin^2\\theta+\\cos^2\\theta$?",
      alternativas:["A) $0$","B) $2$","C) $1$","D) Depende de $\\theta$"],
      respuesta:"C", solucion:"Identidad pitagórica fundamental: $\\sin^2\\theta+\\cos^2\\theta=1$." },
    { id:"trig_m2", nivel:"medio", tema:"Matemáticas", subtema:"Funciones Trigonométricas",
      enunciado:"$\\sin\\theta=\\dfrac{4}{5}$, primer cuadrante. ¿$\\cos\\theta$?",
      alternativas:["A) $\\dfrac{3}{5}$","B) $\\dfrac{4}{5}$","C) $\\dfrac{3}{4}$","D) $\\dfrac{5}{3}$"],
      respuesta:"A", solucion:"$\\cos\\theta=\\sqrt{1-\\sin^2\\theta}=\\sqrt{1-\\frac{16}{25}}=\\frac{3}{5}$." },
    { id:"trig_m3", nivel:"medio", tema:"Matemáticas", subtema:"Funciones Trigonométricas",
      enunciado:"¿En qué cuadrante $\\sin\\theta<0$ y $\\cos\\theta>0$?",
      alternativas:["A) I","B) II","C) III","D) IV"],
      respuesta:"D", solucion:"En el IV cuadrante: $\\cos>0$, $\\sin<0$." },
    { id:"trig_d1", nivel:"dificil", tema:"Matemáticas", subtema:"Funciones Trigonométricas",
      enunciado:"Simplifique: $\\dfrac{\\sin^2\\theta-\\cos^2\\theta}{\\sin\\theta+\\cos\\theta}$",
      alternativas:["A) $\\sin\\theta+\\cos\\theta$","B) $\\sin\\theta-\\cos\\theta$","C) $1$","D) $\\tan\\theta$"],
      respuesta:"B", solucion:"$(\\sin\\theta+\\cos\\theta)(\\sin\\theta-\\cos\\theta)$ en el numerador; cancelando con el denominador: $\\sin\\theta-\\cos\\theta$." },
    { id:"trig_d2", nivel:"dificil", tema:"Matemáticas", subtema:"Funciones Trigonométricas",
      enunciado:"Soluciones de $2\\cos^2\\theta-\\cos\\theta-1=0$ en $[0°,360°]$:",
      alternativas:["A) $60°$ y $180°$","B) $60°,180°,300°$","C) $90°$ y $270°$","D) $0°$ y $180°$"],
      respuesta:"B", solucion:"Sea $u=\\cos\\theta$: $(2u+1)(u-1)=0\\Rightarrow u=-\\frac{1}{2}$ o $u=1$. $\\theta=60°,300°,180°$." },
  ],
};

// ════════════════════════════════════════════
//  CONFIG — subtemas por sección
// ════════════════════════════════════════════
const CONFIG = {
  principiante: {
    label: "Principiante",
    subtemas: [
      { key:"operBasicasNeg",   label:"Operaciones con negativos" },
      { key:"fraccionesNeg",    label:"Fracciones negativas" },
      { key:"factorizacionBasica", label:"Factorización básica" },
      { key:"sumaExpAlg",       label:"Suma de expresiones algebraicas" },
      { key:"enunciadosAlg",    label:"Enunciados a expresiones" },
      { key:"mcdMcm",           label:"MCD y MCM" },
      { key:"decimales",        label:"Cálculo con decimales" },
      { key:"divisibilidad",    label:"Divisibilidad básica" },
      { key:"multExpAlg",       label:"Multiplicación algebraica" },
      { key:"despejarX",        label:"Despejar x" },
      { key:"angulosNotables",  label:"Ángulos notables" },
    ]
  },
  razonamientoMatematico: {
    label: "Razonamiento Matemático",
    total: 15,
    subtemas: [
      { key:"sucesiones",        label:"Sucesiones" },
      { key:"razonLogico",       label:"Razonamiento Lógico" },
      { key:"planteoEcuaciones", label:"Planteo de Ecuaciones" },
      { key:"fracciones",        label:"Fracciones" },
      { key:"tantoPorCiento",    label:"Tanto por ciento" },
    ]
  },
  matematicas: {
    label: "Matemáticas",
    total: 15,
    subtemas: [
      { key:"operAlgebraicas",   label:"Operaciones Algebraicas" },
      { key:"angulosTriangulo",  label:"Suma de ángulos en el triángulo" },
      { key:"pitagoras",         label:"Teorema de Pitágoras" },
      { key:"trigonometria",     label:"Funciones Trigonométricas" },
    ]
  }
};
